// =====================================================
// ★ STEP 1: このファイルの内容を既存の単語データの末尾
//           （j1_u0, j1_u1 などの定義の後）に貼り付ける
// ★ STEP 2: dbオブジェクトの3箇所を書き換える（下記参照）
// =====================================================


// ===== 中1：文法3練習「疑問詞」=====
// db内: {tag:"grammar",label:"文法3",title:"疑問詞",words:[]}
// → words:[] を words:j1_grammar3 に変更
const j1_grammar3 = [
  {en:"What",kana:"<span class='accent'>ホ</span>ワット",ja:"なに",tip:"物・事を聞くときに使う"},
  {en:"Where",kana:"<span class='accent'>ホ</span>ウェア",ja:"どこ",tip:"場所を聞くときに使う"},
  {en:"When",kana:"<span class='accent'>ホ</span>ウェン",ja:"いつ",tip:"時を聞くときに使う"},
  {en:"Who",kana:"<span class='accent'>フ</span>ー",ja:"だれ",tip:"人を聞くときに使う"},
  {en:"Why",kana:"<span class='accent'>ホ</span>ワイ",ja:"なぜ",tip:"理由を聞くときに使う"},
  {en:"Which",kana:"<span class='accent'>ホ</span>ウィッチ",ja:"どちらの",tip:"選択を聞くときに使う"},
  {en:"How",kana:"<span class='accent'>ハ</span>ウ",ja:"どのように",tip:"方法・様子を聞く"},
  {en:"How much",kana:"ハウ <span class='accent'>マ</span>ッチ",ja:"いくらの",tip:"値段や量を聞く"},
  {en:"How many",kana:"ハウ <span class='accent'>メ</span>ニー",ja:"どれだけの（数の）",tip:"数を聞くときに使う"},
  {en:"What time",kana:"ホワット <span class='accent'>タ</span>イム",ja:"何時",tip:"時刻を聞く"},
  {en:"What day",kana:"ホワット <span class='accent'>デ</span>イ",ja:"何曜日（いつ）",tip:"曜日を聞く"},
  {en:"How tall",kana:"ハウ <span class='accent'>ト</span>ール",ja:"背の高さ",tip:"身長を聞くときに"},
  {en:"How high",kana:"ハウ <span class='accent'>ハ</span>イ",ja:"高さ",tip:"高さを聞くときに"},
  {en:"How far",kana:"ハウ <span class='accent'>ファ</span>ー",ja:"遠さ（距離）",tip:"距離を聞くときに"},
  {en:"How often",kana:"ハウ <span class='accent'>オ</span>フン",ja:"頻度",tip:"何回・どのくらいの頻度か"},
  {en:"How old",kana:"ハウ <span class='accent'>オ</span>ールド",ja:"年齢",tip:"年齢を聞くときに"},
  {en:"What year",kana:"ホワット <span class='accent'>イ</span>ア",ja:"何年",tip:"年を聞くときに"},
  {en:"What month",kana:"ホワット <span class='accent'>マ</span>ンス",ja:"何月",tip:"月を聞くときに"},
  {en:"What is this?",kana:"ホワット イズ <span class='accent'>ズ</span>ィス",ja:"これは何ですか？",tip:"What疑問文の基本形"},
  {en:"Where do you live?",kana:"ホウェア ドゥ ユー <span class='accent'>リ</span>ヴ",ja:"あなたはどこに住んでいますか？",tip:"Where疑問文の基本形"},
  {en:"When does it start?",kana:"ホウェン ダズ イット <span class='accent'>ス</span>タート",ja:"それはいつ始まりますか？",tip:"When疑問文の基本形"},
  {en:"Who is that girl?",kana:"フー イズ ザット <span class='accent'>ガ</span>ール",ja:"あの女の子は誰ですか？",tip:"Who疑問文の基本形"},
  {en:"Why do you study English?",kana:"ホワイ ドゥ ユー <span class='accent'>ス</span>タディ イングリッシュ",ja:"あなたはなぜ英語を勉強するのですか？",tip:"Why疑問文の基本形"},
  {en:"How does he go to school?",kana:"ハウ ダズ ヒー ゴウ トゥ <span class='accent'>ス</span>クール",ja:"彼はどうやって学校へ行きますか？",tip:"How疑問文の基本形"},
  {en:"How much is this book?",kana:"ハウ マッチ イズ ズィス <span class='accent'>ブ</span>ック",ja:"この本はいくらですか？",tip:"How much＝値段を聞く"},
  {en:"How many cars do you have?",kana:"ハウ メニー カーズ ドゥ ユー <span class='accent'>ハ</span>ヴ",ja:"あなたは何台の車を持っていますか？",tip:"How many＝数を聞く"},
  {en:"What time does class start?",kana:"ホワット タイム ダズ クラス <span class='accent'>ス</span>タート",ja:"何時にクラスは始まりますか？",tip:"What time疑問文"},
  {en:"What day is English?",kana:"ホワット デイ イズ <span class='accent'>イ</span>ングリッシュ",ja:"英語（の授業）は何曜日ですか？",tip:"What day疑問文"},
  {en:"How tall are you?",kana:"ハウ トール アー <span class='accent'>ユ</span>ー",ja:"あなたの背の高さは？",tip:"身長を聞く定番"},
  {en:"How high is Tokyo Sky Tree?",kana:"ハウ ハイ イズ <span class='accent'>ト</span>ーキョースカイツリー",ja:"東京スカイツリーの高さは？",tip:"How high疑問文"},
  {en:"How far is your school?",kana:"ハウ ファー イズ ユア <span class='accent'>ス</span>クール",ja:"あなたの学校の距離は？",tip:"How far疑問文"},
  {en:"How often do you study English?",kana:"ハウ オフン ドゥ ユー スタディ <span class='accent'>イ</span>ングリッシュ",ja:"あなたはどんな頻度で英語を勉強しますか？",tip:"How often疑問文"},
  {en:"How old are you?",kana:"ハウ オールド アー <span class='accent'>ユ</span>ー",ja:"あなたは何才ですか？",tip:"年齢を聞く定番"},
  {en:"What year is Tokyo Olympic?",kana:"ホワット イア イズ トーキョー <span class='accent'>オ</span>リンピック",ja:"何年に東京オリンピックはありますか？",tip:"What year疑問文"},
  {en:"What month is school festival?",kana:"ホワット マンス イズ スクール <span class='accent'>フェ</span>スティバル",ja:"何月に文化祭はありますか？",tip:"What month疑問文"},
];

// ===== 中1：UNIT4単語「Friends in New Zealand」=====
// db内: {tag:"unit",label:"UNIT 4",title:"Friends in New Zealand",words:[]}
// → words:[] を words:j1_u4 に変更
const j1_u4 = [
  {en:"New Zealand",kana:"ニュー <span class='accent'>ジ</span>ーランド",ja:"ニュージーランド",tip:"南半球の島国！羊が多いことで有名"},
  {en:"puppy",kana:"<span class='accent'>パ</span>ピー",ja:"子犬",tip:"baby dogともいう！かわいい"},
  {en:"puppies",kana:"<span class='accent'>パ</span>ピーズ",ja:"子犬たち",tip:"puppyの複数形。yをiに変えてes！"},
  {en:"of",kana:"<span class='accent'>オ</span>ヴ",ja:"〜の、〜の所有の",tip:"one of ～＝〜の一つ"},
  {en:"someday",kana:"<span class='accent'>サ</span>ムデイ",ja:"いつか",tip:"未来のいつかを表す"},
  {en:"lot",kana:"<span class='accent'>ロ</span>ット",ja:"多くの、塊",tip:"a lot of ～＝たくさんの〜"},
  {en:"they",kana:"<span class='accent'>ゼ</span>イ",ja:"彼らは、彼女らが",tip:"複数の人・物を指す"},
  {en:"animal",kana:"<span class='accent'>ア</span>ニマル",ja:"どうぶつ",tip:"アニマルのanimal"},
  {en:"visit",kana:"<span class='accent'>ヴ</span>ィジット",ja:"ほうもん、訪問する",tip:"visit Japan＝日本を訪れる"},
  {en:"Japan",kana:"ジャ<span class='accent'>パ</span>ン",ja:"にほん、日本",tip:"日本！アクセントは後ろ"},
  {en:"many",kana:"<span class='accent'>メ</span>ニー",ja:"おお、多くの",tip:"many books＝たくさんの本"},
  {en:"one of",kana:"ワン <span class='accent'>オ</span>ヴ",ja:"の一つ",tip:"one of my friends＝友達の一人"},
  {en:"a lot of",kana:"ア ロット <span class='accent'>オ</span>ヴ",ja:"たくさんの",tip:"a lot of＝manyと同じ意味！"},
  {en:"How many",kana:"ハウ <span class='accent'>メ</span>ニー",ja:"いくつ／何個",tip:"数を聞くときの定番表現"},
  {en:"they're",kana:"<span class='accent'>ゼ</span>イア",ja:"they areの略",tip:"they are＝they're"},
  {en:"noon",kana:"<span class='accent'>ヌ</span>ーン",ja:"正午、昼",tip:"12時ちょうどのこと"},
  {en:"last",kana:"<span class='accent'>ラ</span>スト",ja:"この前の、先の",tip:"last week＝先週"},
  {en:"like",kana:"<span class='accent'>ラ</span>イク",ja:"この、好む",tip:"like this＝このような"},
  {en:"o'clock",kana:"オ<span class='accent'>ク</span>ロック",ja:"〜時",tip:"It's three o'clock.＝3時です"},
  {en:"netball",kana:"<span class='accent'>ネ</span>ットボール",ja:"ネットボール",tip:"ニュージーランドで人気のスポーツ！"},
  {en:"time",kana:"<span class='accent'>タ</span>イム",ja:"時、〜回",tip:"What time is it?＝何時ですか？"},
  {en:"afternoon",kana:"アフター<span class='accent'>ヌ</span>ーン",ja:"午後",tip:"good afternoon＝こんにちは"},
  {en:"sport",kana:"<span class='accent'>ス</span>ポーツ",ja:"スポーツ",tip:"そのままスポーツ！"},
  {en:"a.m.",kana:"<span class='accent'>エ</span>イエム",ja:"午前",tip:"ante meridiemのラテン語略"},
  {en:"p.m.",kana:"<span class='accent'>ピ</span>ーエム",ja:"午後",tip:"post meridiemのラテン語略"},
  {en:"basketball",kana:"<span class='accent'>バ</span>スケットボール",ja:"バスケットボール",tip:"バスケのbasketball！"},
  {en:"sounds",kana:"<span class='accent'>サ</span>ウンズ",ja:"音",tip:"That sounds fun!＝楽しそう！"},
  {en:"front",kana:"<span class='accent'>フ</span>ロント",ja:"前、正面",tip:"in front of～＝〜の前に"},
  {en:"nervous",kana:"<span class='accent'>ナ</span>ーヴァス",ja:"神経質な、びくびくして",tip:"緊張してるときにも使う！"},
  {en:"worry",kana:"<span class='accent'>ワ</span>ーリー",ja:"心配させる、憂慮させる",tip:"Don't worry!＝心配しないで！"},
  {en:"yourself",kana:"ユア<span class='accent'>セ</span>ルフ",ja:"自分自身",tip:"enjoy yourself＝楽しんでね"},
  {en:"sheep",kana:"<span class='accent'>シ</span>ープ",ja:"ヒツジ",tip:"複数形もsheep！変化なし"},
  {en:"kiwi",kana:"<span class='accent'>キ</span>ウイ",ja:"キウイ",tip:"ニュージーランドの国鳥でもある！"},
  {en:"right",kana:"<span class='accent'>ラ</span>イト",ja:"右に",tip:"turn right＝右に曲がる"},
  {en:"turn",kana:"<span class='accent'>タ</span>ーン",ja:"曲がる、回る、変化する",tip:"ターンするのturn"},
  {en:"please",kana:"<span class='accent'>プ</span>リーズ",ja:"喜ばせる",tip:"Yes, please.＝はい、お願いします"},
  {en:"look",kana:"<span class='accent'>ル</span>ック",ja:"見る",tip:"look at ～＝〜を見る"},
  {en:"enjoy oneself",kana:"エン<span class='accent'>ジ</span>ョイ ワンセルフ",ja:"楽しく過ごす",tip:"Enjoy yourself!＝楽しんで！"},
  {en:"look at",kana:"ルック <span class='accent'>ア</span>ット",ja:"を見る",tip:"look at the blackboard＝黒板を見て"},
  {en:"fun",kana:"<span class='accent'>ファ</span>ン",ja:"楽しみ",tip:"That's fun!＝楽しい！"},
  {en:"long",kana:"<span class='accent'>ロ</span>ング",ja:"長い",tip:"ロングのlong"},
  {en:"song",kana:"<span class='accent'>ソ</span>ング",ja:"歌、歌唱",tip:"ソングのsong"},
  {en:"fine",kana:"<span class='accent'>フ</span>ァイン",ja:"元気な、晴れた",tip:"I'm fine.＝元気です"},
  {en:"pet",kana:"<span class='accent'>ペ</span>ット",ja:"ペット",tip:"ペットのpet"},
  {en:"stop",kana:"<span class='accent'>ス</span>トップ",ja:"止める",tip:"stop＝ストップ！"},
  {en:"eat",kana:"<span class='accent'>イ</span>ート",ja:"食べる",tip:"eat breakfast＝朝食を食べる"},
  {en:"sad",kana:"<span class='accent'>サ</span>ッド",ja:"悲しい",tip:"I'm sad.＝悲しいです"},
  {en:"eel",kana:"<span class='accent'>イ</span>ール",ja:"うなぎ",tip:"ニュージーランドにも川うなぎが！"},
  {en:"gift",kana:"<span class='accent'>ギ</span>フト",ja:"贈り物、贈答品",tip:"ギフトのgift"},
  {en:"bench",kana:"<span class='accent'>ベ</span>ンチ",ja:"ベンチ",tip:"ベンチのbench"},
  {en:"picture",kana:"<span class='accent'>ピ</span>クチャー",ja:"絵、写真",tip:"take a picture＝写真を撮る"},
  {en:"kitchen",kana:"<span class='accent'>キ</span>ッチン",ja:"台所",tip:"キッチンのkitchen"},
  {en:"table",kana:"<span class='accent'>テ</span>イブル",ja:"机",tip:"テーブルのtable"},
  {en:"all",kana:"<span class='accent'>オ</span>ール",ja:"全部、全員、全て、みな",tip:"all of us＝私たち全員"},
  {en:"poster",kana:"<span class='accent'>ポ</span>スター",ja:"ポスター",tip:"ポスターのposter"},
  {en:"age",kana:"<span class='accent'>エ</span>イジ",ja:"年齢、年数",tip:"What is your age?＝年齢は？"},
  {en:"movie",kana:"<span class='accent'>ム</span>ービー",ja:"映画、映像作品",tip:"ムービーのmovie"},
  {en:"student",kana:"<span class='accent'>ス</span>チューデント",ja:"生徒、学生",tip:"スチューデントのstudent"},
  {en:"much",kana:"<span class='accent'>マ</span>ッチ",ja:"たくさん",tip:"very much＝とても"},
  {en:"starter",kana:"<span class='accent'>ス</span>ターター",ja:"始める人",tip:"start＋erで「始める人」"},
  {en:"famous",kana:"<span class='accent'>フ</span>ェイマス",ja:"有名な",tip:"famousな人＝有名人"},
  {en:"tell",kana:"<span class='accent'>テ</span>ル",ja:"に話す、に対して話す",tip:"tell me＝私に教えて"},
  {en:"elementary school",kana:"エレメンタリー <span class='accent'>ス</span>クール",ja:"小学校",tip:"elementaryは「基礎の」という意味"},
  {en:"subject",kana:"<span class='accent'>サ</span>ブジェクト",ja:"科目、題目",tip:"What subject do you like?＝何の科目が好き？"},
  {en:"junior high school",kana:"ジュニア ハイ <span class='accent'>ス</span>クール",ja:"中学校、中等学校",tip:"juniorは「年少の」という意味"},
  {en:"everyone",kana:"<span class='accent'>エ</span>ヴリワン",ja:"みんな",tip:"Hello, everyone!＝みなさんこんにちは"},
  {en:"big",kana:"<span class='accent'>ビ</span>ッグ",ja:"大きい",tip:"ビッグのbig"},
  {en:"player",kana:"<span class='accent'>プ</span>レイヤー",ja:"選手",tip:"play＋erで「する人」"},
  {en:"very much",kana:"<span class='accent'>ヴ</span>ェリー マッチ",ja:"とても",tip:"Thank you very much.＝大変ありがとう"},
  {en:"every day",kana:"<span class='accent'>エ</span>ヴリ デイ",ja:"毎日",tip:"every day＝毎日（副詞句）"},
];

// ===== 中2：文法3練習「不定詞」=====
// ※ dbは既に words:g_j2_3 と書かれているので変数名を g_j2_3 にしています
// db内: {tag:"grammar",label:"文法3",title:"不定詞",words:g_j2_3}
// → 既に正しく参照されています。この変数を定義するだけでOK！
const g_j2_3 = [
  {en:"I like to swim.",kana:"アイ ライク トゥ <span class='accent'>ス</span>ウィム",ja:"私は泳ぐことが好きです。",tip:"like to＋動詞原形＝〜することが好き"},
  {en:"We want to go to New York.",kana:"ウィ ウォント トゥ ゴウ トゥ ニュー <span class='accent'>ヨ</span>ーク",ja:"私たちはニューヨークに行きたいです。",tip:"want to＋動詞原形＝〜したい"},
  {en:"He tried to open the box.",kana:"ヒー トライド トゥ <span class='accent'>オ</span>ープン ザ ボックス",ja:"彼はその箱を開けようと試みました",tip:"try to＋動詞原形＝〜しようとする"},
  {en:"To play tennis is my hobby.",kana:"トゥ プレイ <span class='accent'>テ</span>ニス イズ マイ ホビー",ja:"テニスをすることは私の趣味です。",tip:"To＋動詞原形が主語になれる！"},
  {en:"To go to school is difficult.",kana:"トゥ ゴウ トゥ <span class='accent'>ス</span>クール イズ ディフィカルト",ja:"学校へ行くことは難しいです。",tip:"不定詞が主語のパターン"},
  {en:"I like to sleep.",kana:"アイ ライク トゥ <span class='accent'>ス</span>リープ",ja:"私は眠ることが好きです。",tip:"like to＋動詞原形"},
  {en:"I would like to listen to music.",kana:"アイ ウッド ライク トゥ リスン トゥ <span class='accent'>ミ</span>ュージック",ja:"私は音楽を聞きたいです。",tip:"would like to＝〜したい（丁寧）"},
  {en:"We tried to close the window.",kana:"ウィ トライド トゥ クロウズ ザ <span class='accent'>ウ</span>ィンドウ",ja:"私たちはその窓を閉めようとしました。",tip:"tried to＝〜しようとした（過去）"},
  {en:"To read books is fun.",kana:"トゥ リード ブックス イズ <span class='accent'>ファ</span>ン",ja:"本を読むことは楽しいです。",tip:"To read＝読むこと（名詞的用法）"},
  {en:"To study English is difficult.",kana:"トゥ スタディ イングリッシュ イズ <span class='accent'>デ</span>ィフィカルト",ja:"英語を勉強することは難しいです。",tip:"難しいことを認めつつ頑張ろう！"},
  {en:"I have English homework to do.",kana:"アイ ハヴ イングリッシュ ホームワーク トゥ <span class='accent'>ド</span>ゥ",ja:"私はするべき英語の宿題があります。",tip:"名詞＋to do＝するべき〜（形容詞的用法）"},
  {en:"She wants something to drink.",kana:"シー ウォンツ サムスィング トゥ <span class='accent'>ド</span>リンク",ja:"彼女は何か飲み物が欲しいです。",tip:"something to drink＝何か飲むもの"},
  {en:"I have many apples to eat.",kana:"アイ ハヴ メニー アップルズ トゥ <span class='accent'>イ</span>ート",ja:"私は食べる（べき）りんごがたくさんあります。",tip:"to eat＝食べるための（形容詞的用法）"},
  {en:"We need something to throw.",kana:"ウィ ニード サムスィング トゥ <span class='accent'>ス</span>ロウ",ja:"私たちは何か投げるものが必要です。",tip:"something to throw＝何か投げるもの"},
  {en:"Kyoto has many places to visit.",kana:"キョウトウ ハズ メニー プレイシズ トゥ <span class='accent'>ヴ</span>ィジット",ja:"京都には訪れるべきたくさんの場所があります。",tip:"places to visit＝訪れるべき場所"},
  {en:"I have math questions to think.",kana:"アイ ハヴ マス クウェスチョンズ トゥ <span class='accent'>ス</span>ィンク",ja:"私は考えるべき数学の問題があります。",tip:"questions to think＝考えるべき問題"},
  {en:"He needs something to throw.",kana:"ヒー ニーズ サムスィング トゥ <span class='accent'>ス</span>ロウ",ja:"彼は何か投げる物が必要です。",tip:"needsはneedの三単現"},
  {en:"I have many books to read.",kana:"アイ ハヴ メニー ブックス トゥ <span class='accent'>リ</span>ード",ja:"私は読む（べき）本がたくさんあります。",tip:"to read＝読むための（形容詞的用法）"},
  {en:"We have friends to help us.",kana:"ウィ ハヴ フレンズ トゥ ヘルプ <span class='accent'>ア</span>ス",ja:"私達は（私達を）助けてくれる友達がいます。",tip:"to help us＝私たちを助けてくれる"},
  {en:"They have time to study.",kana:"ゼイ ハヴ タイム トゥ <span class='accent'>ス</span>タディ",ja:"彼らには勉強するための時間があります。",tip:"time to study＝勉強する時間"},
  {en:"I study hard to be a doctor.",kana:"アイ スタディ ハード トゥ ビー ア <span class='accent'>ド</span>クター",ja:"私は医者になるために勉強します。",tip:"to be＝〜になるために（副詞的用法・目的）"},
  {en:"You woke up early to take the bus.",kana:"ユー ウォウク アップ アーリー トゥ テイク ザ <span class='accent'>バ</span>ス",ja:"あなたはそのバスに乗るために早く起きました。",tip:"to take＝乗るために（副詞的用法・目的）"},
  {en:"The teacher came to Japan to teach English.",kana:"ザ ティーチャー ケイム トゥ ジャパン トゥ ティーチ <span class='accent'>イ</span>ングリッシュ",ja:"その先生は英語を教えるために日本に来ました。",tip:"to teach＝教えるために（副詞的用法・目的）"},
  {en:"I am very happy to meet you.",kana:"アイ アム ヴェリー ハッピー トゥ ミート <span class='accent'>ユ</span>ー",ja:"私はあなたに会えてとてもうれしいです。",tip:"happy to＝〜してうれしい（副詞的用法・感情の原因）"},
  {en:"I am sad to hear the news.",kana:"アイ アム サッド トゥ ヒア ザ <span class='accent'>ニ</span>ュース",ja:"私はその知らせを聞いて悲しいです。",tip:"sad to hear＝聞いて悲しい"},
  {en:"I run every day to be a soccer player.",kana:"アイ ラン エヴリ デイ トゥ ビー ア <span class='accent'>サ</span>ッカープレイヤー",ja:"私はサッカー選手になるために走ります。",tip:"to be＝〜になるために"},
  {en:"You slept early to go to school.",kana:"ユー スレプト アーリー トゥ ゴウ トゥ <span class='accent'>ス</span>クール",ja:"あなたは学校へ行くために早く寝ました。",tip:"to go＝行くために（目的）"},
  {en:"They went to China to build a bridge.",kana:"ゼイ ウェント トゥ チャイナ トゥ ビルド ア <span class='accent'>ブ</span>リッジ",ja:"彼らは橋を作るために中国に行きました。",tip:"to build＝建てるために"},
  {en:"He is very happy to talk to you.",kana:"ヒー イズ ヴェリー ハッピー トゥ トーク トゥ <span class='accent'>ユ</span>ー",ja:"彼はあなたと話せてとてもうれしいです。",tip:"happy to talk＝話せてうれしい"},
  {en:"My mother is happy to hear the news.",kana:"マイ マザー イズ ハッピー トゥ ヒア ザ <span class='accent'>ニ</span>ュース",ja:"私の母はその知らせを聞いてうれしいです。",tip:"happy to hear＝聞いてうれしい"},
  {en:"My mother came home at seven.",kana:"マイ マザー ケイム ホウム アット <span class='accent'>セ</span>ヴン",ja:"私の母は7時に帰ってきました。",tip:"came home＝家に帰ってきた（過去）"},
  {en:"The book is by the bed.",kana:"ザ ブック イズ バイ ザ <span class='accent'>ベ</span>ッド",ja:"その本はベッドの側にあります。",tip:"by＝〜のそばに"},
  {en:"He slept during the class.",kana:"ヒー スレプト デュアリング ザ <span class='accent'>ク</span>ラス",ja:"彼は授業の間に寝ました。",tip:"during＝〜の間に"},
  {en:"I stayed at a hotel for three days.",kana:"アイ ステイド アット ア ホウテル フォア スリー <span class='accent'>デ</span>イズ",ja:"私はホテルに3日間滞在しました。",tip:"for three days＝3日間"},
  {en:"I will finish homework in two days.",kana:"アイ ウィル フィニッシュ ホウムワーク イン トゥー <span class='accent'>デ</span>イズ",ja:"私は2日以内に宿題を終えます。",tip:"in two days＝2日以内に"},
  {en:"My brother is the tallest of our family.",kana:"マイ ブラザー イズ ザ トーレスト オヴ アワ <span class='accent'>ファ</span>ミリー",ja:"私の弟が私達の家族の中で一番背が高い。",tip:"the tallest＝最も背が高い（最上級）"},
  {en:"There was an apple on the table.",kana:"ゼア ウォズ アン アップル オン ザ <span class='accent'>テ</span>イブル",ja:"机の上にリンゴがありました。",tip:"There was＝〜があった（過去）"},
  {en:"He has been studying since last Friday.",kana:"ヒー ハズ ビーン スタディング スィンス ラスト <span class='accent'>フ</span>ライデイ",ja:"彼は前の金曜日から勉強を続けています。",tip:"has been〜ing＝ずっと〜している（現在完了進行形）"},
  {en:"He will work till six P.M.",kana:"ヒー ウィル ワーク ティル シックス <span class='accent'>ピ</span>ーエム",ja:"彼は6時まで働くつもりです。",tip:"till＝〜まで"},
  {en:"He ran toward the school.",kana:"ヒー ラン トウォード ザ <span class='accent'>ス</span>クール",ja:"彼は学校に向って走りました。",tip:"toward＝〜に向かって"},
  {en:"My sister arrived with a smile.",kana:"マイ シスター アライヴド ウィズ ア <span class='accent'>ス</span>マイル",ja:"私の姉は笑顔と共に到着しました。",tip:"with a smile＝笑顔で"},
  {en:"He left home without money.",kana:"ヒー レフト ホウム ウィザウト <span class='accent'>マ</span>ニー",ja:"彼はお金なしに家を出ていきました。",tip:"without＝〜なしに"},
  {en:"The ball is above you.",kana:"ザ ボール イズ アバヴ <span class='accent'>ユ</span>ー",ja:"そのボールはあなたの上にあります。",tip:"above＝〜の上に"},
  {en:"There is a bicycle across the road.",kana:"ゼア イズ ア バイシクル アクロス ザ <span class='accent'>ロ</span>ウド",ja:"道の向こうに自転車があります。",tip:"across＝〜の向こうに"},
  {en:"She stands among the trees.",kana:"シー スタンズ アマング ザ <span class='accent'>ト</span>リーズ",ja:"彼女は木々の間に立っています。",tip:"among＝〜の間に（3つ以上）"},
];

// ===== 中3：文法2練習「不定詞」=====
// db内: {tag:"grammar",label:"文法2",title:"不定詞",words:[]}
// → words:[] を words:j3_grammar2 に変更
const j3_grammar2 = [
  {en:"I like to swim.",kana:"アイ ライク トゥ <span class='accent'>ス</span>ウィム",ja:"私は泳ぐことが好きです。",tip:"like to＋動詞原形＝〜することが好き"},
  {en:"We want to go to New York.",kana:"ウィ ウォント トゥ ゴウ トゥ ニュー <span class='accent'>ヨ</span>ーク",ja:"私たちはニューヨークに行きたいです。",tip:"want to＋動詞原形＝〜したい"},
  {en:"He tried to open the box.",kana:"ヒー トライド トゥ <span class='accent'>オ</span>ープン ザ ボックス",ja:"彼はその箱を開けようと試みました",tip:"try to＋動詞原形＝〜しようとする"},
  {en:"To play tennis is my hobby.",kana:"トゥ プレイ <span class='accent'>テ</span>ニス イズ マイ ホビー",ja:"テニスをすることは私の趣味です。",tip:"不定詞が主語になれる！"},
  {en:"To go to school is difficult.",kana:"トゥ ゴウ トゥ <span class='accent'>ス</span>クール イズ ディフィカルト",ja:"学校へ行くことは難しいです。",tip:"不定詞が主語のパターン"},
  {en:"I like to sleep.",kana:"アイ ライク トゥ <span class='accent'>ス</span>リープ",ja:"私は眠ることが好きです。",tip:"like to＋動詞原形"},
  {en:"I would like to listen to music.",kana:"アイ ウッド ライク トゥ リスン トゥ <span class='accent'>ミ</span>ュージック",ja:"私は音楽を聞きたいです。",tip:"would like to＝〜したい（丁寧）"},
  {en:"We tried to close the window.",kana:"ウィ トライド トゥ クロウズ ザ <span class='accent'>ウ</span>ィンドウ",ja:"私たちはその窓を閉めようとしました。",tip:"tried to＝〜しようとした（過去）"},
  {en:"To read books is fun.",kana:"トゥ リード ブックス イズ <span class='accent'>ファ</span>ン",ja:"本を読むことは楽しいです。",tip:"To read＝読むこと（名詞的用法）"},
  {en:"To study English is difficult.",kana:"トゥ スタディ イングリッシュ イズ <span class='accent'>デ</span>ィフィカルト",ja:"英語を勉強することは難しいです。",tip:"難しいけど頑張ろう！"},
  {en:"I have English homework to do.",kana:"アイ ハヴ イングリッシュ ホームワーク トゥ <span class='accent'>ド</span>ゥ",ja:"私はするべき英語の宿題があります。",tip:"名詞＋to do＝するべき〜（形容詞的用法）"},
  {en:"She wants something to drink.",kana:"シー ウォンツ サムスィング トゥ <span class='accent'>ド</span>リンク",ja:"彼女は何か飲み物が欲しいです。",tip:"something to drink＝何か飲むもの"},
  {en:"I have many apples to eat.",kana:"アイ ハヴ メニー アップルズ トゥ <span class='accent'>イ</span>ート",ja:"私は食べる（べき）りんごがたくさんあります。",tip:"to eat＝食べるための（形容詞的用法）"},
  {en:"We need something to throw.",kana:"ウィ ニード サムスィング トゥ <span class='accent'>ス</span>ロウ",ja:"私たちは何か投げるものが必要です。",tip:"something to throw＝何か投げるもの"},
  {en:"Kyoto has many places to visit.",kana:"キョウトウ ハズ メニー プレイシズ トゥ <span class='accent'>ヴ</span>ィジット",ja:"京都には訪れるべきたくさんの場所があります。",tip:"places to visit＝訪れるべき場所"},
  {en:"I have math questions to think.",kana:"アイ ハヴ マス クウェスチョンズ トゥ <span class='accent'>ス</span>ィンク",ja:"私は考えるべき数学の問題があります。",tip:"questions to think＝考えるべき問題"},
  {en:"He needs something to throw.",kana:"ヒー ニーズ サムスィング トゥ <span class='accent'>ス</span>ロウ",ja:"彼は何か投げる物が必要です。",tip:"needsはneedの三単現"},
  {en:"I have many books to read.",kana:"アイ ハヴ メニー ブックス トゥ <span class='accent'>リ</span>ード",ja:"私は読む（べき）本がたくさんあります。",tip:"to read＝読むための（形容詞的用法）"},
  {en:"We have friends to help us.",kana:"ウィ ハヴ フレンズ トゥ ヘルプ <span class='accent'>ア</span>ス",ja:"私達は（私達を）助けてくれる友達がいます。",tip:"to help us＝私たちを助けてくれる"},
  {en:"They have time to study.",kana:"ゼイ ハヴ タイム トゥ <span class='accent'>ス</span>タディ",ja:"彼らには勉強するための時間があります。",tip:"time to study＝勉強する時間"},
  {en:"I study hard to be a doctor.",kana:"アイ スタディ ハード トゥ ビー ア <span class='accent'>ド</span>クター",ja:"私は医者になるために勉強します。",tip:"to be＝〜になるために（副詞的用法・目的）"},
  {en:"You woke up early to take the bus.",kana:"ユー ウォウク アップ アーリー トゥ テイク ザ <span class='accent'>バ</span>ス",ja:"あなたはそのバスに乗るために早く起きました。",tip:"to take＝乗るために（副詞的用法・目的）"},
  {en:"The teacher came to Japan to teach English.",kana:"ザ ティーチャー ケイム トゥ ジャパン トゥ ティーチ <span class='accent'>イ</span>ングリッシュ",ja:"その先生は英語を教えるために日本に来ました。",tip:"to teach＝教えるために（副詞的用法・目的）"},
  {en:"I am very happy to meet you.",kana:"アイ アム ヴェリー ハッピー トゥ ミート <span class='accent'>ユ</span>ー",ja:"私はあなたに会えてとてもうれしいです。",tip:"happy to＝〜してうれしい（副詞的用法・感情の原因）"},
  {en:"I am sad to hear the news.",kana:"アイ アム サッド トゥ ヒア ザ <span class='accent'>ニ</span>ュース",ja:"私はその知らせを聞いて悲しいです。",tip:"sad to hear＝聞いて悲しい"},
  {en:"I run every day to be a soccer player.",kana:"アイ ラン エヴリ デイ トゥ ビー ア <span class='accent'>サ</span>ッカープレイヤー",ja:"私はサッカー選手になるために走ります。",tip:"to be＝〜になるために"},
  {en:"You slept early to go to school.",kana:"ユー スレプト アーリー トゥ ゴウ トゥ <span class='accent'>ス</span>クール",ja:"あなたは学校へ行くために早く寝ました。",tip:"to go＝行くために（目的）"},
  {en:"They went to China to build a bridge.",kana:"ゼイ ウェント トゥ チャイナ トゥ ビルド ア <span class='accent'>ブ</span>リッジ",ja:"彼らは橋を作るために中国に行きました。",tip:"to build＝建てるために"},
  {en:"He is very happy to talk to you.",kana:"ヒー イズ ヴェリー ハッピー トゥ トーク トゥ <span class='accent'>ユ</span>ー",ja:"彼はあなたと話せてとてもうれしいです。",tip:"happy to talk＝話せてうれしい"},
  {en:"My mother is happy to hear the news.",kana:"マイ マザー イズ ハッピー トゥ ヒア ザ <span class='accent'>ニ</span>ュース",ja:"私の母はその知らせを聞いてうれしいです。",tip:"happy to hear＝聞いてうれしい"},
  {en:"My mother came home at seven.",kana:"マイ マザー ケイム ホウム アット <span class='accent'>セ</span>ヴン",ja:"私の母は7時に帰ってきました。",tip:"came home＝家に帰ってきた（過去）"},
  {en:"The book is by the bed.",kana:"ザ ブック イズ バイ ザ <span class='accent'>ベ</span>ッド",ja:"その本はベッドの側にあります。",tip:"by＝〜のそばに"},
  {en:"He slept during the class.",kana:"ヒー スレプト デュアリング ザ <span class='accent'>ク</span>ラス",ja:"彼は授業の間に寝ました。",tip:"during＝〜の間に"},
  {en:"I stayed at a hotel for three days.",kana:"アイ ステイド アット ア ホウテル フォア スリー <span class='accent'>デ</span>イズ",ja:"私はホテルに3日間滞在しました。",tip:"for three days＝3日間"},
  {en:"I will finish homework in two days.",kana:"アイ ウィル フィニッシュ ホウムワーク イン トゥー <span class='accent'>デ</span>イズ",ja:"私は2日以内に宿題を終えます。",tip:"in two days＝2日以内に"},
  {en:"My brother is the tallest of our family.",kana:"マイ ブラザー イズ ザ トーレスト オヴ アワ <span class='accent'>ファ</span>ミリー",ja:"私の弟が私達の家族の中で一番背が高い。",tip:"the tallest＝最も背が高い（最上級）"},
  {en:"There was an apple on the table.",kana:"ゼア ウォズ アン アップル オン ザ <span class='accent'>テ</span>イブル",ja:"机の上にリンゴがありました。",tip:"There was＝〜があった（過去）"},
  {en:"He has been studying since last Friday.",kana:"ヒー ハズ ビーン スタディング スィンス ラスト <span class='accent'>フ</span>ライデイ",ja:"彼は前の金曜日から勉強を続けています。",tip:"has been〜ing＝ずっと〜している（現在完了進行形）"},
  {en:"He will work till six P.M.",kana:"ヒー ウィル ワーク ティル シックス <span class='accent'>ピ</span>ーエム",ja:"彼は6時まで働くつもりです。",tip:"till＝〜まで"},
  {en:"He ran toward the school.",kana:"ヒー ラン トウォード ザ <span class='accent'>ス</span>クール",ja:"彼は学校に向って走りました。",tip:"toward＝〜に向かって"},
  {en:"My sister arrived with a smile.",kana:"マイ シスター アライヴド ウィズ ア <span class='accent'>ス</span>マイル",ja:"私の姉は笑顔と共に到着しました。",tip:"with a smile＝笑顔で"},
  {en:"He left home without money.",kana:"ヒー レフト ホウム ウィザウト <span class='accent'>マ</span>ニー",ja:"彼はお金なしに家を出ていきました。",tip:"without＝〜なしに"},
  {en:"The ball is above you.",kana:"ザ ボール イズ アバヴ <span class='accent'>ユ</span>ー",ja:"そのボールはあなたの上にあります。",tip:"above＝〜の上に"},
  {en:"There is a bicycle across the road.",kana:"ゼア イズ ア バイシクル アクロス ザ <span class='accent'>ロ</span>ウド",ja:"道の向こうに自転車があります。",tip:"across＝〜の向こうに"},
  {en:"She stands among the trees.",kana:"シー スタンズ アマング ザ <span class='accent'>ト</span>リーズ",ja:"彼女は木々の間に立っています。",tip:"among＝〜の間に（3つ以上）"},
];

// =====================================================
// ★ STEP 2: dbオブジェクトの以下3箇所を書き換える
//
// 【中1 文法3】
//   変更前: {tag:"grammar",label:"文法3",title:"疑問詞",words:[]},
//   変更後: {tag:"grammar",label:"文法3",title:"疑問詞",words:j1_grammar3},
//
// 【中1 UNIT4】
//   変更前: {tag:"unit",label:"UNIT 4",title:"Friends in New Zealand",words:[]},
//   変更後: {tag:"unit",label:"UNIT 4",title:"Friends in New Zealand",words:j1_u4},
//
// 【中2 文法3】 ※ 変数名 g_j2_3 はdbと一致済み。定義を追加するだけでOK！
//   変更不要（既に words:g_j2_3 と書いてある）
//
// 【中3 文法2】
//   変更前: {tag:"grammar",label:"文法2",title:"不定詞",words:[]},
//   変更後: {tag:"grammar",label:"文法2",title:"不定詞",words:j3_grammar2},
//
// =====================================================
